// Command authzgen generates the permission catalog from the authorization
// model DSL, so code and policy cannot disagree within a commit.
//
// Convention: relations prefixed "can_" are permissions (checkable);
// everything else is an assignable role (tuple-write territory) and is
// skipped. That prefix is the machine-readable line between the two, which
// is why the model uses it consistently.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"
	"text/template"

	"github.com/openfga/language/pkg/go/transformer"
)

const permissionPrefix = "can_"

type permission struct {
	GoName   string
	Type     string
	Relation string
}

func main() {
	in := flag.String("in", "model.fga", "path to the model DSL")
	out := flag.String("out", "permissions.go", "path to the generated catalog")
	pkg := flag.String("package", "authz", "package name")
	flag.Parse()

	dsl, err := os.ReadFile(*in)
	if err != nil {
		log.Fatalf("read %s: %v", *in, err)
	}
	model, err := transformer.TransformDSLToProto(string(dsl))
	if err != nil {
		log.Fatalf("parse %s: %v", *in, err)
	}

	var perms []permission
	for _, td := range model.GetTypeDefinitions() {
		for rel := range td.GetRelations() {
			if !strings.HasPrefix(rel, permissionPrefix) {
				continue
			}
			perms = append(perms, permission{
				GoName:   goName(td.GetType()) + goName(strings.TrimPrefix(rel, permissionPrefix)),
				Type:     td.GetType(),
				Relation: rel,
			})
		}
	}
	// Deterministic order keeps regeneration diffs empty when nothing changed.
	sort.Slice(perms, func(i, j int) bool { return perms[i].GoName < perms[j].GoName })

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, map[string]any{"Package": *pkg, "Permissions": perms}); err != nil {
		log.Fatalf("render: %v", err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("gofmt: %v\n%s", err, buf.String())
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	fmt.Fprintf(os.Stderr, "authzgen: %d permissions -> %s\n", len(perms), *out)
}

// goName converts snake_case identifiers to exported Go names.
func goName(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' })
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

var tmpl = template.Must(template.New("catalog").Parse(`// Code generated by tools/authzgen from model.fga. DO NOT EDIT.

package {{ .Package }}

var (
{{- range .Permissions }}
	{{ .GoName }} = Permission{ {{ printf "%q" .Type }}, {{ printf "%q" .Relation }} }
{{- end }}
)

// Permissions returns the full catalog. Adapters validate it against the
// deployed model at startup.
func Permissions() []Permission {
	return []Permission{
{{- range .Permissions }}
		{{ .GoName }},
{{- end }}
	}
}
`))
